from typing import Protocol

from core.domain.protocols.entity_protocol import AggregateRoot


class Repository[T: AggregateRoot](Protocol):
    async def create(self, entity: T) -> None: ...

    async def find_by_id(self, entity_id: str) -> T | None: ...

    async def find_all(self) -> list[T]: ...

    async def delete(self, entity_id: str) -> None: ...

    async def update(self, entity: T) -> None: ...
