from typing import Protocol


class Repository[T](Protocol):
    def create(self, entity: T) -> None: ...

    def find_by_id(self, entity_id: str) -> T | None: ...

    def find_all(self) -> list[T]: ...

    def delete(self, entity_id: str) -> None: ...

    def update(self, entity: T) -> None: ...
